
server :
  port : 0

eureka:
  client:
    enabled: false

spring:
  application:
    name: product-service
  datasource :
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ordermsa
    username : root
    password : 1234

  jpa :
    database : mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto : create
    show-sql : true
  kafka:
    kafka-server: localhost:9092
    consumer:
#      groupid는 컨슈머 그룹을 식별하는 id로서, 동일한 그룹id를 가진 컨슈머들은 메시지를 분담해서 consume한다
#      그런데 컨슈머가 서로 다른 group-id를 가지고 한 토픽을 consume하면 메시지를 각기 수신하는 pub/sub 효과 발생
      group-id: product-group
#      가장 처음 들어온 메시지부터 읽기 시작(latest: 현 시점 이후로 들어오는 메시지만 읽음)
      auto-offset-reset: earliest
  servlet :
    multipart :
      max-file-size : 1000MB
      max-request-size: 1000MB

cloud:
  aws:
    credentials:
      access-key: xxxxxxxxxx
      secret-key: yyyyyyyyyy
    region:
      static: ap-northeast-2
    s3:
      bucket: jin-ordersystem-bucket
