
server :
  port : 8080

eureka:
  client:
    enabled: false

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              # - 'http://localhost:3000'
              - 'https://www.jin98.shop'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowedCredentials: true
      routes:
        - id: member-service
          predicates:
            - Path=/member-service/**
          filters:
#            첫번째 접두어를 제거한 후에 member-service 서버로 http 요청 전달
            - StripPrefix=1
            # eureka에 등록된 이름이 아닌, k8s의 서비스명을 배포시 사용, lb는 유레카 경로
          uri: http://member-service
        - id: ordering-service
          predicates:
            - Path=/ordering-service/**
          filters:
#            첫번째 접두어를 제거한 후에 member-service 서버로 http 요청 전달
            - StripPrefix=1
#            eureka에 등록된 member-service라는 이름으로 http요청 전달
          uri: http://ordering-service
        - id: product-service
          predicates:
            - Path=/product-service/**
          filters:
#            첫번째 접두어를 제거한 후에 member-service 서버로 http 요청 전달
            - StripPrefix=1
#            eureka에 등록된 member-service라는 이름으로 http요청 전달
          uri: http://product-service

jwt:
  expirationAt : 1000 #1000분
  secretKeyAt : YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5
  expirationRt : 10000 #1000분
  secretKeyRt : YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5

server:
  port: 8080

eureka:
  client:
    enabled: false

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              # - 'http://localhost:3000'
              - 'https://www.kishi0211.store'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowedCredentials: true
      routes:
        - id: member-service
          predicates:
            - Path=/member-service/**
          filters:
            - StripPrefix=1
          # eureka에 등록된 이름이 아닌, k8s의 서비스명을 배포시 사용
          uri: http://member-service
        - id: product-service
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1
          uri: http://product-service
        - id: ordering-service
          predicates:
            - Path=/ordering-service/**
          filters:
            - StripPrefix=1
          uri: http://ordering-service

jwt:
  expirationAt: 1000
  secretKeyAt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5

  expirationRt: 10000
  secretKeyRt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5